# Functions

In [1]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

In [2]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


In [3]:
def add_numbers(x,y,z=None,flag=False):
    if (flag):
        print("Flag is true")
    if (z==None):
        return x+y
    else:
        return x+y+z
        
print(add_numbers(1,3,flag=True))   

Flag is true
4


# Types and sequence

In [6]:
type("This is a string")

str

In [7]:
type(None)

NoneType

In [8]:
type(1)

int

In [9]:
type(1.0)

float

In [10]:
type(add_numbers)

function

tuples are immutable data structure which cannot be altered

In [11]:
x = (1, 'a', 2, 'b')
type(x)

tuple

In [12]:
x = (1,2)
type(x)

tuple

lists are mutable data structure

In [13]:
l = [1,2,3]
type(l)

list

In [18]:
l.append('a')
print(l)

[1, 2, 3, 'a', 'a', 'a', 'a']


In [19]:
for item in l:
    print(item)

1
2
3
a
a
a
a


using the index operator

In [21]:
i=0
while( i != len(l) ):
    print(l[i])
    i = i + 1

1
2
3
a
a
a
a


Use + to concatenate lists

In [22]:
print(l+[0,3])

[1, 2, 3, 'a', 'a', 'a', 'a', 0, 3]


use * to repeat list

In [23]:
l*2

[1, 2, 3, 'a', 'a', 'a', 'a', 1, 2, 3, 'a', 'a', 'a', 'a']

Use the in operator to check if something is inside a list.

In [24]:
"a" in l

True

 Use bracket notation to slice a string

In [25]:
x = 'This is a string'
x[0]

'T'

In [26]:
x[0:3]

'Thi'

In [27]:
x[0:]

'This is a string'

In [28]:
x[-3:-1]

'in'

In [29]:
firstname="Qianjia"
lastname='Jiang'
name = firstname+' '+lastname
print(name)
print(lastname*2)


Qianjia Jiang
JiangJiang


In [30]:
first= name[0:7]
last=name[-5:]
print(first)
print(last)

Qianjia
Jiang


split returns a list of all the words in a string, or a list split on a specific character

In [32]:
first = name.split(' ')[0]
print(first)

Qianjia


Make sure you convert objects to strings before concatenating.

In [33]:
first_2 = first+2
print(first_2)

TypeError: must be str, not int

In [34]:
first_2 = first+str(2)
print(first_2)

Qianjia2


Dictionaries associate keys with values.

In [35]:
dict_name = {'Jiang':'Qianjia','Dog':'Hund'}
print(dict_name['Jiang'])

Qianjia


In [36]:
for name in dict_name:
    print(dict_name[name])

Qianjia
Hund


In [37]:
for synonym in dict_name.values():
    print(synonym)

Qianjia
Hund


In [38]:
for name, synonym in dict_name.items():
    print(name)
    print(synonym)

Jiang
Qianjia
Dog
Hund


You can unpack a sequence into different variables:

In [39]:
x = ('Qianjia','Jiang','168')
firstname,lastname,height=x
print(firstname,height)

Qianjia 168


Python has a built in method for convenient string formatting.

In [42]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement= '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                            sales_record['num_items'],
                            sales_record['price'],
                            sales_record['price']*sales_record["num_items"]))

Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


# dates and time

In [43]:
import datetime
import time

In [44]:
time.time()

1592329055.828945

In [45]:
dtnow = datetime.datetime.fromtimestamp(time.time())
dtnow

datetime.datetime(2020, 6, 16, 19, 38, 5, 620259)

In [46]:
dtnow.year,dtnow.month,dtnow.hour

(2020, 6, 19)

In [47]:
delta = datetime.timedelta(days = 100)

In [48]:
delta

datetime.timedelta(100)

In [49]:
today = datetime.date.today()
today

datetime.date(2020, 6, 16)

In [50]:
today-delta

datetime.date(2020, 3, 8)

# Objects and map()

An example of a class in python:

In [54]:
class Person():
    department = "Biology"
    
    def set_name(self,new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location


In [56]:
person = Person()
person.set_name('Qianjia Jiang')
person.set_location('Germany')

print('{} live in {} and study in department of {}'.format(person.name,person.location,person.department))

Qianjia Jiang live in Germany and study in department of Biology


Here's an example of mapping the `min` function between two lists.

map(function,iterable)
function: It is a function to which map passes each element of given iterable.
iterable : It is a iterable which is to be mapped.
Return: a list of the results after applying the given function to each item of a given iterable (list, tuple etc.) 

In [59]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(max, store1, store2)
cheapest

In [60]:
for item in cheapest:
    print(item)

10.0
11.1
12.34
2.34


# Lambda and List Comprehensions

In [61]:
my_function = lambda a, b, c : a + b

In [62]:
my_function(1,2,3)

3

(lambda Arguement:expression)(applied to lambda fucntion)

In [152]:
(lambda a,b,c:a+b)(1,2,3)

3

In [63]:
my_list = []
for number in range(0, 10):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0, 2, 4, 6, 8]

In [65]:
my_list = [number for number in range(0,10) if number % 2 == 0]
my_list

[0, 2, 4, 6, 8]

# Get familiar with numpy

In [66]:
import numpy as np

In [67]:
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [70]:
mylist = np.array([[1,2,3],[4,5,6]])
mylist

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
mylist.shape

(2, 3)

In [75]:
n = np.arange(0,30,4)
n

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [76]:
m = n.reshape(4,2)
m

array([[ 0,  4],
       [ 8, 12],
       [16, 20],
       [24, 28]])

linspace returns evenly spaced numbers over a specified interval.

In [79]:
a = np.linspace(0,1,10)
a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

`resize` changes the shape and size of array in-place. reshape has similar function but not in place.

In [81]:
a.resize(2,5)
a

array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444],
       [0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]])

ones returns a new array of given shape and type, filled with ones.

In [83]:
o = np.ones((2,3))
o

array([[1., 1., 1.],
       [1., 1., 1.]])

In [84]:
o = np.zeros((2,3))
o

array([[0., 0., 0.],
       [0., 0., 0.]])

eye returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [87]:
o = np.eye(5)
o

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

'diag' extracts a diagonal or constructs a diagonal array.

In [92]:
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [93]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [94]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [95]:
p = np.ones([2, 3])
p

array([[1., 1., 1.],
       [1., 1., 1.]])

In [96]:
np.vstack([p, 3*p])

array([[1., 1., 1.],
       [1., 1., 1.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [97]:
np.vstack([3*p, 2*p])

array([[3., 3., 3.],
       [3., 3., 3.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [98]:
np.hstack([3*p, 2*p])

array([[3., 3., 3., 2., 2., 2.],
       [3., 3., 3., 2., 2., 2.]])

<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [101]:
x = np.array([1,2,3])
y = np.array([2,3,4])
x.dot(y)

20

In [112]:
z = np.array([y, y**2])
print(z)
print(len(z))

[[ 2  3  4]
 [ 4  9 16]]
2


In [113]:
z.shape

(2, 3)

In [114]:
z.T.shape

(3, 2)

In [115]:
z.T

array([[ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [116]:
z.dtype
z

array([[ 2,  3,  4],
       [ 4,  9, 16]])

In [117]:
g = z.astype('f')
g.dtype

dtype('float32')

In [119]:
z.resize(3,2)
z

array([[ 2,  3],
       [ 4,  4],
       [ 9, 16]])

In [120]:
z.resize(1,6)
z

array([[ 2,  3,  4,  4,  9, 16]])

In [121]:
z.max()

16

In [122]:
z.min()

2

In [123]:
z.argmax()

5

In [124]:
z.argmin()

0

In [131]:
z_new = np.vstack([z*2,z])
z_new.resize(3,4)
z_new

array([[ 4,  6,  8,  8],
       [18, 32,  2,  3],
       [ 4,  4,  9, 16]])

In [134]:
z_new[2,3]

16

In [135]:
z_new[1,0:]

array([18, 32,  2,  3])

In [136]:
z_new[z_new>10]

array([18, 32, 16])

# Copying Data

Be careful with copying and modifying arrays in NumPy!


`z2` is a slice of `z_new`

In [137]:
z2 = z_new[:2,:2]

In [138]:
z2

array([[ 4,  6],
       [18, 32]])

In [139]:
z2[:]=0
z2

array([[0, 0],
       [0, 0]])

In [140]:
z_new

array([[ 0,  0,  8,  8],
       [ 0,  0,  2,  3],
       [ 4,  4,  9, 16]])

To avoid this, use z_new.copy to create a copy that will not affect the original array

In [141]:
z_copy = z_new.copy()
z_copy

array([[ 0,  0,  8,  8],
       [ 0,  0,  2,  3],
       [ 4,  4,  9, 16]])

In [142]:
z_copy2 = z_copy[:2,:2]
z_copy2[:]=100
z_copy2

array([[100, 100],
       [100, 100]])

In [143]:
z_copy

array([[100, 100,   8,   8],
       [100, 100,   2,   3],
       [  4,   4,   9,  16]])

In [144]:
z_new

array([[ 0,  0,  8,  8],
       [ 0,  0,  2,  3],
       [ 4,  4,  9, 16]])

# Iterating Over Arrays

In [145]:
test = np.random.randint(0, 10, (4,3))
test

array([[4, 0, 9],
       [8, 3, 2],
       [2, 0, 0],
       [2, 6, 8]])

In [146]:
for row in test:
    print(row)

[4 0 9]
[8 3 2]
[2 0 0]
[2 6 8]


In [147]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [4 0 9]
row 1 is [8 3 2]
row 2 is [2 0 0]
row 3 is [2 6 8]


In [148]:
test2 = test**2
test2

array([[16,  0, 81],
       [64,  9,  4],
       [ 4,  0,  0],
       [ 4, 36, 64]])

In [149]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[4 0 9] + [16  0 81] = [20  0 90]
[8 3 2] + [64  9  4] = [72 12  6]
[2 0 0] + [4 0 0] = [6 0 0]
[2 6 8] + [ 4 36 64] = [ 6 42 72]


In [156]:
lowercase = 'abcdefg'
for i in lowercase:
    for j in lowercase:
        print(i+j)

aa
ab
ac
ad
ae
af
ag
ba
bb
bc
bd
be
bf
bg
ca
cb
cc
cd
ce
cf
cg
da
db
dc
dd
de
df
dg
ea
eb
ec
ed
ee
ef
eg
fa
fb
fc
fd
fe
ff
fg
ga
gb
gc
gd
ge
gf
gg


In [158]:
['a']+[1]

['a', 1]

In [159]:
type(lambda x: x+1)

function

In [161]:
r = np.arange(0,36,1).reshape(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [162]:
r[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [163]:
r[:,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [164]:
r.reshape(36)[::-7]

array([35, 28, 21, 14,  7,  0])